# Generated by Django 3.1.1 on 2020-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.ImageField(upload_to='documents/')),
                ('predicted_text', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
