# Generated by Django 3.1.1 on 2020-10-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201002_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
